spring:
    application:
        name: shipping-service
    data:
        mongodb:
            host: localhost
            port: 27017
            database: eventsourcing

    kafka:
        bootstrap-servers: localhost:9092   # Kafka broker addresses

        consumer:
            group-id: shipping-service    # Group ID for the consumer
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer  # Deserializer for the key
            value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer  # Wraps JsonDeserializer for error handling
            properties:
                spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
                spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
                spring.json.trusted.packages: "*"  # You can restrict this to your package for added security

server:
    port: 8082